services:
  - type: web
    name: Arnav_FinPulse_Backend
    env: python
    region: oregon
    plan: free
    github:
      repo: arnavnoncode/Arnav_FinPulse
      branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn finpulse.api.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.7"
